"use client";

import { useEffect, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Alert, AlertDescription } from "@/components/ui/alert";
import {
  ArrowLeft,
  User,
  Mail,
  Phone,
  Briefcase,
  CheckCircle2,
  MapPin,
  Globe,
} from "lucide-react";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";

export default function ProfessionalRegistrationPage() {
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    phone: "",
    address: "",
    description: "",
    profession: "",
    website: "",
    termsAccepted: false,
  });
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [loading, setLoading] = useState(false);
  const router = useRouter();
  const searchParams = useSearchParams();

  useEffect(() => {
    const oauthError = searchParams.get("error");
    if (oauthError) {
      setError(oauthError);
    }
  }, [searchParams]);

  const handleGoogleSignup = () => {
    if (!formData.termsAccepted) {
      setError("Please accept Terms of Service and Privacy Policy before continuing with Google.");
      return;
    }
    window.location.href = "/api/auth/google?mode=signup&role=PROFESSIONAL_ADMIN";
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { id, value } = e.target;
    setFormData((prev) => ({ ...prev, [id]: value }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setSuccess("");
    setLoading(true);

    // Validation
    if (!formData.termsAccepted) {
      setError("You must accept the Terms of Service and Privacy Policy");
      setLoading(false);
      return;
    }

    try {
      // Submit registration inquiry (password will be generated by admin during approval)
      const response = await fetch("/api/registration-inquiries", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          type: "PROFESSIONAL",
          name: formData.name,
          email: formData.email,
          phone: formData.phone,
          location: formData.address,
          profession: formData.profession,
          aboutMe: formData.description,
          website: formData.website || undefined,
          termsAccepted: formData.termsAccepted,
          termsAcceptedAt: new Date().toISOString(),
        }),
      });

      const result = await response.json();

      if (result.success) {
        setSuccess(
          "Registration request submitted successfully! You will receive a confirmation email and our team will review your application within 24 hours. A secure password will be provided upon approval.",
        );
        setTimeout(() => {
          router.push("/login/professional");
        }, 3000);
      } else {
        setError(result.error || "Registration request failed");
      }
    } catch (error) {
      setError("An unexpected error occurred. Please try again.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen w-full flex flex-col lg:flex-row font-sans bg-slate-200">
      {/* --- LEFT SIDE: FORM --- */}
      <div className="flex-1 flex flex-col justify-center relative w-full px-4 sm:px-6 lg:px-12 py-10 lg:py-0 z-10">
        {/* Top Header */}
        <div className="absolute top-0 left-0 w-full px-4 sm:px-6 lg:px-12 py-4 lg:py-6 flex justify-between items-center z-20">
          <Link href="/" className="flex items-center space-x-2 group">
            <div className="rounded-md text-primary">
              <Image
                src="/logo-tranparent.png"
                alt="DigiSence Logo"
                width={32}
                height={32}
                className="h-8 w-auto"
              />
            </div>
            <span className="font-bold text-xl text-slate-800 tracking-tight hidden sm:block">
              DigiSence
            </span>
          </Link>
          <Button
            onClick={() => router.push("/register")}
            variant="ghost"
            size="sm"
            className="hover:bg-slate-100 border rounded-full py-1 px-3 text-slate-600 transition-colors font-medium"
          >
            <ArrowLeft className="h-4 w-4 mr-2" /> Back
          </Button>
        </div>

        {/* Content Wrapper */}
        <div className="w-full max-w-md mx-auto space-y-6 sm:space-y-8 mt-12 sm:mt-4">
          {/* Header Text */}
          <div className="text-center space-y-2 px-2">
            <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-800">
              Professional Account
            </h1>
            <p className="text-sm sm:text-base text-slate-500">
              Expand your professional reach with us
            </p>
          </div>

          {/* Form Area */}
          <CardContent className="p-0 space-y-5">
            <form onSubmit={handleSubmit} className="space-y-5">
              {/* Name */}
              <div className="space-y-2">
                <Label
                  htmlFor="name"
                  className="text-xs font-bold uppercase text-slate-500 tracking-wider"
                >
                  Full Name
                </Label>
                <div className="relative group">
                  <User className="absolute left-3 top-3 h-4 w-4 text-slate-400 group-focus-within:text-primary transition-colors" />
                  <Input
                    id="name"
                    type="text"
                    value={formData.name}
                    onChange={handleChange}
                    required
                    disabled={loading}
                    placeholder="Your Full Name"
                    className="pl-9 h-11 bg-white shadow-none focus-visible:ring-2 focus-visible:ring-primary/20"
                  />
                </div>
              </div>

              {/* Email */}
              <div className="space-y-2">
                <Label
                  htmlFor="email"
                  className="text-xs font-bold uppercase text-slate-500 tracking-wider"
                >
                  Email Address
                </Label>
                <div className="relative group">
                  <Mail className="absolute left-3 top-3 h-4 w-4 text-slate-400 group-focus-within:text-primary transition-colors" />
                  <Input
                    id="email"
                    type="email"
                    value={formData.email}
                    onChange={handleChange}
                    required
                    disabled={loading}
                    placeholder="professional@example.com"
                    className="pl-9 h-11 bg-white shadow-none focus-visible:ring-2 focus-visible:ring-primary/20"
                  />
                </div>
              </div>

              {/* Phone & Profession Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label
                    htmlFor="phone"
                    className="text-xs font-bold uppercase text-slate-500 tracking-wider"
                  >
                    Phone
                  </Label>
                  <div className="relative group">
                    <Phone className="absolute left-3 top-3 h-4 w-4 text-slate-400 group-focus-within:text-primary transition-colors" />
                    <Input
                      id="phone"
                      type="tel"
                      value={formData.phone}
                      onChange={handleChange}
                      required
                      disabled={loading}
                      placeholder="+1 234 567 890"
                      className="pl-9 h-11 bg-white shadow-none focus-visible:ring-2 focus-visible:ring-primary/20"
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <Label
                    htmlFor="profession"
                    className="text-xs font-bold uppercase text-slate-500 tracking-wider"
                  >
                    Profession
                  </Label>
                  <div className="relative group">
                    <Briefcase className="absolute left-3 top-3 h-4 w-4 text-slate-400 group-focus-within:text-primary transition-colors" />
                    <Input
                      id="profession"
                      type="text"
                      value={formData.profession}
                      onChange={handleChange}
                      required
                      disabled={loading}
                      placeholder="Developer"
                      className="pl-9 h-11 bg-white shadow-none focus-visible:ring-2 focus-visible:ring-primary/20"
                    />
                  </div>
                </div>
              </div>

              {/* Description */}
              <div className="space-y-2">
                <Label
                  htmlFor="description"
                  className="text-xs font-bold uppercase text-slate-500 tracking-wider"
                >
                  Professional Description
                </Label>
                <Textarea
                  id="description"
                  value={formData.description}
                  onChange={(e) =>
                    setFormData((prev) => ({
                      ...prev,
                      description: e.target.value,
                    }))
                  }
                  required
                  disabled={loading}
                  placeholder="Tell us about yourself and your professional background..."
                  className="h-24 shadow-none bg-white focus-visible:ring-2 focus-visible:ring-primary/20 resize-none"
                />
              </div>

              {/* Address & Website Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label
                    htmlFor="address"
                    className="text-xs font-bold uppercase text-slate-500 tracking-wider"
                  >
                    Address
                  </Label>
                  <div className="relative group">
                    <MapPin className="absolute left-3 top-3 h-4 w-4 text-slate-400 group-focus-within:text-primary transition-colors" />
                    <Input
                      id="address"
                      type="text"
                      value={formData.address}
                      onChange={handleChange}
                      required
                      disabled={loading}
                      placeholder="City, Country"
                      className="pl-9 h-11 bg-white shadow-none focus-visible:ring-2 focus-visible:ring-primary/20"
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <Label
                    htmlFor="website"
                    className="text-xs font-bold uppercase text-slate-500 tracking-wider"
                  >
                    Website (Optional)
                  </Label>
                  <div className="relative group">
                    <Globe className="absolute left-3 top-3 h-4 w-4 text-slate-400 group-focus-within:text-primary transition-colors" />
                    <Input
                      id="website"
                      type="url"
                      value={formData.website}
                      onChange={handleChange}
                      disabled={loading}
                      placeholder="https://yourwebsite.com"
                      className="pl-9 h-11 bg-white shadow-none focus-visible:ring-2 focus-visible:ring-primary/20"
                    />
                  </div>
                </div>
              </div>

              {/* Terms Acceptance */}
              <div className="flex items-start space-x-3 pt-2">
                <Checkbox
                  id="termsAccepted"
                  checked={formData.termsAccepted}
                  onCheckedChange={(checked) =>
                    setFormData((prev) => ({
                      ...prev,
                      termsAccepted: checked as boolean,
                    }))
                  }
                  disabled={loading}
                  className="mt-1"
                />
                <div className="text-sm text-slate-600 leading-snug">
                  <Label htmlFor="termsAccepted" className="cursor-pointer">
                    I agree to the{" "}
                    <Button
                      variant="link"
                      className="p-0 h-auto text-primary hover:text-primary/80 font-semibold"
                    >
                      Terms of Service
                    </Button>{" "}
                    and{" "}
                    <Button
                      variant="link"
                      className="p-0 h-auto text-primary hover:text-primary/80 font-semibold"
                    >
                      Privacy Policy
                    </Button>
                  </Label>
                  
                </div>
              </div>

              {/* Alerts */}
              {error && (
                <Alert
                  variant="destructive"
                  className="py-3 text-sm border-red-100 bg-red-50/50"
                >
                  <AlertDescription>{error}</AlertDescription>
                </Alert>
              )}

              {success && (
                <Alert className="py-3 text-sm border-green-100 bg-green-50 text-green-700">
                  <CheckCircle2 className="h-4 w-4" />
                  <AlertDescription className="ml-2">
                    {success}
                  </AlertDescription>
                </Alert>
              )}

              {/* Submit Button */}
              <Button
                type="button"
                variant="outline"
                className="w-full h-11 border-slate-300 bg-white hover:bg-slate-50 text-slate-700"
                onClick={handleGoogleSignup}
                disabled={loading}
              >
                Sign up with Google
              </Button>

              <Button
                type="submit"
                className="w-full h-11  bg-slate-800 cursor-pointer hover:opacity-90 text-white font-medium transition-all transform hover:-translate-y-0.5"
                disabled={loading}
              >
                {loading
                  ? "Creating Account..."
                  : "Create Professional Account"}
              </Button>

              {/* Login Link */}
              <div className="text-center text-sm text-slate-500 pt-2">
                Already have an account?{" "}
                <Button
                  type="button"
                  variant="link"
                  className="p-0 h-auto text-primary hover:text-primary/80 font-semibold"
                  onClick={() => router.push("/login/professional")}
                >
                  Log in
                </Button>
              </div>
            </form>
          </CardContent>
        </div>
      </div>

      {/* --- RIGHT SIDE: IMAGE (Desktop Only) --- */}
      <div className="hidden lg:flex flex-1 relative bg-slate-900 m-0 lg:m-4 lg:rounded-2xl overflow-hidden shadow-2xl">
        <div
          className="absolute inset-0 bg-cover bg-center transition-transform duration-[10s] ease-in-out hover:scale-105"
          style={{ backgroundImage: "url('/login-bg.svg')" }}
        />
        <div className="absolute inset-0 bg-linear-to-b from-slate-900/40 via-slate-900/20 to-slate-900/90 pointer-events-none"></div>

        <div className="relative z-10 flex flex-col justify-between h-full w-full py-16 px-10 xl:px-20">
          <div className="flex-1"></div>

          <div className="flex items-center justify-center py-10">
            <div className="shrink-0 drop-shadow-2xl animate-pulse-slow">
              <img
                src="/pro-svg.png"
                alt="Professional Icon"
                className=" w-auto object-contain opacity-90"
              />
            </div>
          </div>

          <div className="text-center mb-12 space-y-4">
            <h3 className="text-4xl xl:text-5xl font-bold text-white tracking-tight drop-shadow-md">
              Grow Your Professional Presence Online
            </h3>
            <p className="text-base text-gray-200 opacity-90 leading-relaxed max-w-lg mx-auto font-light">
              Join thousands of professionals expanding their digital presence
              with our powerful tools and analytics.
            </p>
          </div>
          <div className="flex-1"></div>
        </div>
      </div>
    </div>
  );
}
